"""update_weather_miner_scores_with_detailed_cols_and_constraint

Revision ID: 02f5e86d4224
Revises: 50344f0c595d
Create Date: 2025-05-26 17:42:47.851744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02f5e86d4224'
down_revision: Union[str, None] = '50344f0c595d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.alter_column('task_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Name of the task being scored',
               existing_nullable=True)
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               comment='Unique ID for the specific task instance',
               existing_nullable=True)
        batch_op.alter_column('score',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               comment='Array of scores, typically per UID',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of score creation',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               comment='Status of the scoring process',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.create_table_comment(
        'Table to store scores for various tasks.',
        existing_comment=None
    )

    with op.batch_alter_table('weather_miner_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('variable_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('valid_time_utc', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.create_index('idx_wms_lead_hours', ['lead_hours'], unique=False)
        batch_op.create_index('idx_wms_valid_time_utc', ['valid_time_utc'], unique=False)
        batch_op.create_index('idx_wms_variable_level', ['variable_level'], unique=False)
        batch_op.create_unique_constraint('uq_wms_response_scoretype_lead_var_time', ['response_id', 'score_type', 'lead_hours', 'variable_level', 'valid_time_utc'])
        batch_op.create_table_comment(
        'Stores calculated scores (e.g., gfs_rmse, era5_rmse) for each miner response, detailed by lead time and variable.',
        existing_comment='Stores calculated scores (e.g., gfs_rmse, era5_rmse) for each miner response.'
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_scores', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Stores calculated scores (e.g., gfs_rmse, era5_rmse) for each miner response.',
        existing_comment='Stores calculated scores (e.g., gfs_rmse, era5_rmse) for each miner response, detailed by lead time and variable.'
    )
        batch_op.drop_constraint('uq_wms_response_scoretype_lead_var_time', type_='unique')
        batch_op.drop_index('idx_wms_variable_level')
        batch_op.drop_index('idx_wms_valid_time_utc')
        batch_op.drop_index('idx_wms_lead_hours')
        batch_op.drop_column('valid_time_utc')
        batch_op.drop_column('variable_level')
        batch_op.drop_column('lead_hours')

    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Table to store scores for various tasks.'
    )
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Status of the scoring process',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of score creation',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('score',
               existing_type=postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)),
               comment=None,
               existing_comment='Array of scores, typically per UID',
               existing_nullable=True)
        batch_op.alter_column('task_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Unique ID for the specific task instance',
               existing_nullable=True)
        batch_op.alter_column('task_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Name of the task being scored',
               existing_nullable=True)

    # ### end Alembic commands ###
