"""add_hotkey_index_to_node_table

Revision ID: 45fb64e1ae3c
Revises: 3a4b5c6d7e8f
Create Date: 2025-05-25 22:46:11.813580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45fb64e1ae3c'
down_revision: Union[str, None] = '3a4b5c6d7e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_node_table_hotkey', 'node_table', ['hotkey'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_node_table_hotkey', table_name='node_table')
    # ### end Alembic commands ###
