"""add_uq_constraint_score_table_task_name_task_id

Revision ID: 50344f0c595d
Revises: efec2f9f40a1
Create Date: 2025-05-26 17:04:08.489713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50344f0c595d'
down_revision: Union[str, None] = 'efec2f9f40a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('miner_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miner_hotkey', sa.String(), nullable=False),
    sa.Column('last_active_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('processed_tasks_count', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('miner_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miner_state_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_miner_state_miner_hotkey'), ['miner_hotkey'], unique=True)

    op.create_table('miner_task_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_uuid', sa.String(), nullable=False),
    sa.Column('validator_hotkey', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('payload_cid', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_cid', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('miner_task_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_miner_task_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_miner_task_assignments_task_uuid'), ['task_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_miner_task_assignments_validator_hotkey'), ['validator_hotkey'], unique=False)

    with op.batch_alter_table('node_table', schema=None) as batch_op:
        batch_op.drop_index('idx_node_table_hotkey')

    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.drop_index('idx_score_table_status_created_at')
        batch_op.create_unique_constraint('uq_score_table_task_name_task_id', ['task_name', 'task_id'])

    with op.batch_alter_table('weather_forecast_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_wfr_status_final_score_time_gfs_time')

    with op.batch_alter_table('weather_miner_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_wms_lead_hours')
        batch_op.drop_index('idx_wms_valid_time_utc')
        batch_op.drop_index('idx_wms_variable_level')
        batch_op.drop_constraint('uq_wms_response_scoretype_lead_var_time', type_='unique')
        batch_op.drop_column('variable_level')
        batch_op.drop_column('lead_hours')
        batch_op.drop_column('valid_time_utc')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_time_utc', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lead_hours', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('variable_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('uq_wms_response_scoretype_lead_var_time', ['response_id', 'score_type', 'lead_hours', 'variable_level', 'valid_time_utc'])
        batch_op.create_index('idx_wms_variable_level', ['variable_level'], unique=False)
        batch_op.create_index('idx_wms_valid_time_utc', ['valid_time_utc'], unique=False)
        batch_op.create_index('idx_wms_lead_hours', ['lead_hours'], unique=False)

    with op.batch_alter_table('weather_forecast_runs', schema=None) as batch_op:
        batch_op.create_index('idx_wfr_status_final_score_time_gfs_time', ['status', 'final_scoring_attempted_time', 'gfs_init_time_utc'], unique=False)

    with op.batch_alter_table('score_table', schema=None) as batch_op:
        batch_op.drop_constraint('uq_score_table_task_name_task_id', type_='unique')
        batch_op.create_index('idx_score_table_status_created_at', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('node_table', schema=None) as batch_op:
        batch_op.create_index('idx_node_table_hotkey', ['hotkey'], unique=False)

    with op.batch_alter_table('miner_task_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miner_task_assignments_validator_hotkey'))
        batch_op.drop_index(batch_op.f('ix_miner_task_assignments_task_uuid'))
        batch_op.drop_index(batch_op.f('ix_miner_task_assignments_id'))

    op.drop_table('miner_task_assignments')
    with op.batch_alter_table('miner_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_miner_state_miner_hotkey'))
        batch_op.drop_index(batch_op.f('ix_miner_state_id'))

    op.drop_table('miner_state')
    # ### end Alembic commands ###
