"""initial_schema_from_metadata

Revision ID: 54516f21dc9c
Revises: 
Create Date: 2025-05-08 14:52:39.455906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54516f21dc9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    print("Starting simplified upgrade function for diagnosis...")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Serial ID for the prediction entry'),
    sa.Column('task_name', sa.Text(), nullable=False, comment='Name of the task (e.g., geomagnetic, soil_moisture)'),
    sa.Column('task_id', sa.Text(), nullable=False, comment='ID of the specific task execution'),
    sa.Column('region_id', sa.Text(), nullable=True, comment='For region-specific tasks, the region identifier'),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False, comment='Timestamp for when the prediction was made/is valid for'),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="The model's prediction data"),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp of prediction storage'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores baseline model predictions for various tasks.'
    )
    op.create_index('idx_baseline_task_on_baseline_predictions', 'baseline_predictions', ['task_name', 'task_id'], unique=False)
    op.create_table('geomagnetic_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('miner_uid', sa.Text(), nullable=False),
    sa.Column('miner_hotkey', sa.Text(), nullable=False),
    sa.Column('query_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('ground_truth_value', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('scored_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geomagnetic_predictions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('miner_uid', sa.Text(), nullable=False),
    sa.Column('miner_hotkey', sa.Text(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('query_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gp_miner_hotkey', 'geomagnetic_predictions', ['miner_hotkey'], unique=False)
    op.create_index('idx_gp_miner_uid', 'geomagnetic_predictions', ['miner_uid'], unique=False)
    op.create_index('idx_gp_query_time', 'geomagnetic_predictions', ['query_time'], unique=False)
    op.create_index('idx_gp_status', 'geomagnetic_predictions', ['status'], unique=False)
    op.create_table('node_table',
    sa.Column('uid', sa.Integer(), nullable=False, comment='Unique ID for the node, 0-255'),
    sa.Column('hotkey', sa.Text(), nullable=True, comment='Hotkey of the node'),
    sa.Column('coldkey', sa.Text(), nullable=True, comment='Coldkey of the node'),
    sa.Column('ip', sa.Text(), nullable=True, comment='IP address of the node'),
    sa.Column('ip_type', sa.Text(), nullable=True, comment='IP address type (e.g., IPv4, IPv6)'),
    sa.Column('port', sa.Integer(), nullable=True, comment="Port number for the node's services"),
    sa.Column('incentive', sa.Float(), nullable=True, comment='Current incentive score of the node'),
    sa.Column('stake', sa.Float(), nullable=True, comment='Current stake of the node'),
    sa.Column('trust', sa.Float(), nullable=True, comment='Current trust score of the node'),
    sa.Column('vtrust', sa.Float(), nullable=True, comment='Current validator trust score of the node'),
    sa.Column('protocol', sa.Text(), nullable=True, comment='Protocol version used by the node'),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment="Timestamp of the last update for this node's record"),
    sa.CheckConstraint('uid >= 0 AND uid < 256', name='node_table_uid_check'),
    sa.PrimaryKeyConstraint('uid'),
    comment="Table storing information about registered nodes (miners/validators)."
    )
    op.create_table('score_table',
    sa.Column('task_name', sa.VARCHAR(length=255), nullable=True, comment='Name of the task being scored'),
    sa.Column('task_id', sa.Text(), nullable=True, comment='Unique ID for the specific task instance'),
    sa.Column('score', postgresql.ARRAY(sa.Float()), nullable=True, comment='Array of scores, typically per UID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='Timestamp of score creation'),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=True, comment='Status of the scoring process'),
    comment='Table to store scores for various tasks.'
    )
    op.create_index('idx_score_created_at_on_score_table', 'score_table', ['created_at'], unique=False)
    op.create_table('soil_moisture_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_date', sa.Date(), nullable=False),
    sa.Column('target_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('combined_data', postgresql.BYTEA(), nullable=True),
    sa.Column('sentinel_bounds', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('sentinel_crs', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_cleared_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('array_shape', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_smr_region_date', 'soil_moisture_regions', ['region_date'], unique=False)
    op.create_index('idx_smr_status', 'soil_moisture_regions', ['status'], unique=False)
    op.create_index('idx_smr_target_time', 'soil_moisture_regions', ['target_time'], unique=False)
    op.create_table('weather_forecast_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_initiation_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('target_forecast_time_utc', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('gfs_init_time_utc', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('gfs_input_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('completion_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('final_scoring_attempted_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks each weather forecast run initiated by the validator.'
    )
    op.create_index('idx_wfr_gfs_init_time', 'weather_forecast_runs', ['gfs_init_time_utc'], unique=False)
    op.create_index('idx_wfr_run_init_time', 'weather_forecast_runs', ['run_initiation_time'], unique=False)
    op.create_index('idx_wfr_status', 'weather_forecast_runs', ['status'], unique=False)
    op.create_index('idx_wfr_target_forecast_time', 'weather_forecast_runs', ['target_forecast_time_utc'], unique=False)
    op.create_table('weather_historical_weights',
    sa.Column('miner_hotkey', sa.VARCHAR(length=255), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('score_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['weather_forecast_runs.id'], ondelete='CASCADE'),
    comment='Stores calculated scores and weights for miners on a per-run basis (e.g., initial GFS score).'
    )
    op.create_index('idx_whw_miner_hotkey', 'weather_historical_weights', ['miner_hotkey'], unique=False)
    op.create_index('idx_whw_run_id', 'weather_historical_weights', ['run_id'], unique=False)
    op.create_index('idx_whw_score_type', 'weather_historical_weights', ['score_type'], unique=False)
    op.create_table('soil_moisture_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('miner_uid', sa.Text(), nullable=False),
    sa.Column('miner_hotkey', sa.Text(), nullable=False),
    sa.Column('target_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('surface_sm_pred', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('rootzone_sm_pred', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('surface_sm_truth', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('rootzone_sm_truth', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('surface_rmse', sa.Float(), nullable=True),
    sa.Column('rootzone_rmse', sa.Float(), nullable=True),
    sa.Column('surface_structure_score', sa.Float(), nullable=True),
    sa.Column('rootzone_structure_score', sa.Float(), nullable=True),
    sa.Column('scored_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['soil_moisture_regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_smh_miner_hotkey', 'soil_moisture_history', ['miner_hotkey'], unique=False)
    op.create_index('idx_smh_miner_uid', 'soil_moisture_history', ['miner_uid'], unique=False)
    op.create_index('idx_smh_region_id', 'soil_moisture_history', ['region_id'], unique=False)
    op.create_index('idx_smh_target_time', 'soil_moisture_history', ['target_time'], unique=False)
    op.create_table('soil_moisture_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('miner_uid', sa.Text(), nullable=False),
    sa.Column('miner_hotkey', sa.Text(), nullable=False),
    sa.Column('target_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('surface_sm', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('rootzone_sm', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('uncertainty_surface', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('uncertainty_rootzone', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('sentinel_bounds', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('sentinel_crs', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'sent_to_miner'"), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('next_retry_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['soil_moisture_regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_smp_miner_hotkey', 'soil_moisture_predictions', ['miner_hotkey'], unique=False)
    op.create_index('idx_smp_miner_uid', 'soil_moisture_predictions', ['miner_uid'], unique=False)
    op.create_index('idx_smp_region_id', 'soil_moisture_predictions', ['region_id'], unique=False)
    op.create_index('idx_smp_status', 'soil_moisture_predictions', ['status'], unique=False)
    op.create_index('idx_smp_target_time', 'soil_moisture_predictions', ['target_time'], unique=False)
    op.create_table('weather_ensemble_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_run_id', sa.Integer(), nullable=False),
    sa.Column('creation_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('processing_end_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ensemble_path', sa.Text(), nullable=True),
    sa.Column('ensemble_kerchunk_path', sa.Text(), nullable=True),
    sa.Column('ensemble_verification_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_run_id'], ['weather_forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores ensemble forecast information created by combining multiple miner forecasts.'
    )
    op.create_index('idx_wef_forecast_run_id', 'weather_ensemble_forecasts', ['forecast_run_id'], unique=False)
    op.create_table('weather_miner_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('miner_uid', sa.Integer(), nullable=False),
    sa.Column('miner_hotkey', sa.VARCHAR(length=255), nullable=False),
    sa.Column('response_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('kerchunk_json_url', sa.Text(), nullable=True),
    sa.Column('target_netcdf_url_template', sa.Text(), nullable=True),
    sa.Column('kerchunk_json_retrieved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_hash_computed', sa.VARCHAR(length=64), nullable=True),
    sa.Column('verification_hash_claimed', sa.VARCHAR(length=64), nullable=True),
    sa.Column('verification_passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'received'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_hash_miner', sa.VARCHAR(length=64), nullable=True),
    sa.Column('input_hash_validator', sa.VARCHAR(length=64), nullable=True),
    sa.Column('input_hash_match', sa.Boolean(), nullable=True),
    sa.Column('last_polled_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['weather_forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'miner_uid', name='uq_weather_miner_responses_run_miner'),
    comment='Records miner responses for a specific forecast run. Tracks status through fetch, hash verification, and inference.'
    )
    op.create_index('idx_wmr_job_id', 'weather_miner_responses', ['job_id'], unique=False)
    op.create_index('idx_wmr_miner_hotkey', 'weather_miner_responses', ['miner_hotkey'], unique=False)
    op.create_index('idx_wmr_miner_uid', 'weather_miner_responses', ['miner_uid'], unique=False)
    op.create_index('idx_wmr_run_id', 'weather_miner_responses', ['run_id'], unique=False)
    op.create_index('idx_wmr_status', 'weather_miner_responses', ['status'], unique=False)
    op.create_index('idx_wmr_verification_passed', 'weather_miner_responses', ['verification_passed'], unique=False)
    op.create_table('weather_ensemble_components',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ensemble_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['ensemble_id'], ['weather_ensemble_forecasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['weather_miner_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tracks which miner forecasts are included in an ensemble and their weights.'
    )
    op.create_index('idx_wec_ensemble_id', 'weather_ensemble_components', ['ensemble_id'], unique=False)
    op.create_index('idx_wec_response_id', 'weather_ensemble_components', ['response_id'], unique=False)
    op.create_table('weather_miner_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('miner_uid', sa.Integer(), nullable=False),
    sa.Column('miner_hotkey', sa.VARCHAR(length=255), nullable=False),
    sa.Column('score_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('calculation_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['weather_miner_responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['weather_forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores calculated scores (e.g., gfs_rmse, era5_rmse) for each miner response.'
    )
    op.create_index('idx_wms_calculation_time', 'weather_miner_scores', ['calculation_time'], unique=False)
    op.create_index('idx_wms_miner_hotkey', 'weather_miner_scores', ['miner_hotkey'], unique=False)
    op.create_index('idx_wms_miner_uid', 'weather_miner_scores', ['miner_uid'], unique=False)
    op.create_index('idx_wms_run_id', 'weather_miner_scores', ['run_id'], unique=False)
    op.create_index('idx_wms_score_type', 'weather_miner_scores', ['score_type'], unique=False)
    # ### end Alembic commands ###

    # Manually added operations for functions, triggers, and initial data
    op.execute("""
    CREATE OR REPLACE FUNCTION check_node_table_size()
    RETURNS TRIGGER AS $$
    BEGIN
      IF (SELECT COUNT(*) FROM node_table) >= 256 THEN
        RAISE EXCEPTION 'Cannot insert more than 256 rows into node_table';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER enforce_node_table_size
    BEFORE INSERT ON node_table
    FOR EACH ROW EXECUTE FUNCTION check_node_table_size();
    """)

    op.execute("""
    INSERT INTO node_table (uid)
    SELECT i FROM generate_series(0, 255) AS i
    ON CONFLICT (uid) DO NOTHING;
    """)
    print("Simplified upgrade function finished.")
    pass


def downgrade() -> None:
    print("Starting simplified downgrade function for diagnosis...")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wms_score_type', table_name='weather_miner_scores')
    op.drop_index('idx_wms_run_id', table_name='weather_miner_scores')
    op.drop_index('idx_wms_miner_uid', table_name='weather_miner_scores')
    op.drop_index('idx_wms_miner_hotkey', table_name='weather_miner_scores')
    op.drop_index('idx_wms_calculation_time', table_name='weather_miner_scores')
    op.drop_table('weather_miner_scores')
    op.drop_index('idx_wec_response_id', table_name='weather_ensemble_components')
    op.drop_index('idx_wec_ensemble_id', table_name='weather_ensemble_components')
    op.drop_table('weather_ensemble_components')
    op.drop_index('idx_wmr_verification_passed', table_name='weather_miner_responses')
    op.drop_index('idx_wmr_status', table_name='weather_miner_responses')
    op.drop_index('idx_wmr_run_id', table_name='weather_miner_responses')
    op.drop_index('idx_wmr_miner_uid', table_name='weather_miner_responses')
    op.drop_index('idx_wmr_miner_hotkey', table_name='weather_miner_responses')
    op.drop_index('idx_wmr_job_id', table_name='weather_miner_responses')
    op.drop_table('weather_miner_responses')
    op.drop_index('idx_wef_forecast_run_id', table_name='weather_ensemble_forecasts')
    op.drop_table('weather_ensemble_forecasts')
    op.drop_index('idx_smp_target_time', table_name='soil_moisture_predictions')
    op.drop_index('idx_smp_status', table_name='soil_moisture_predictions')
    op.drop_index('idx_smp_region_id', table_name='soil_moisture_predictions')
    op.drop_index('idx_smp_miner_uid', table_name='soil_moisture_predictions')
    op.drop_index('idx_smp_miner_hotkey', table_name='soil_moisture_predictions')
    op.drop_table('soil_moisture_predictions')
    op.drop_index('idx_smh_target_time', table_name='soil_moisture_history')
    op.drop_index('idx_smh_region_id', table_name='soil_moisture_history')
    op.drop_index('idx_smh_miner_uid', table_name='soil_moisture_history')
    op.drop_index('idx_smh_miner_hotkey', table_name='soil_moisture_history')
    op.drop_table('soil_moisture_history')
    op.drop_index('idx_whw_score_type', table_name='weather_historical_weights')
    op.drop_index('idx_whw_run_id', table_name='weather_historical_weights')
    op.drop_index('idx_whw_miner_hotkey', table_name='weather_historical_weights')
    op.drop_table('weather_historical_weights')
    op.drop_index('idx_wfr_target_forecast_time', table_name='weather_forecast_runs')
    op.drop_index('idx_wfr_status', table_name='weather_forecast_runs')
    op.drop_index('idx_wfr_run_init_time', table_name='weather_forecast_runs')
    op.drop_index('idx_wfr_gfs_init_time', table_name='weather_forecast_runs')
    op.drop_table('weather_forecast_runs')
    op.drop_index('idx_smr_target_time', table_name='soil_moisture_regions')
    op.drop_index('idx_smr_status', table_name='soil_moisture_regions')
    op.drop_index('idx_smr_region_date', table_name='soil_moisture_regions')
    op.drop_table('soil_moisture_regions')
    op.drop_index('idx_score_created_at_on_score_table', table_name='score_table')
    op.drop_table('score_table')
    op.drop_table('node_table')
    op.drop_index('idx_gp_status', table_name='geomagnetic_predictions')
    op.drop_index('idx_gp_query_time', table_name='geomagnetic_predictions')
    op.drop_index('idx_gp_miner_uid', table_name='geomagnetic_predictions')
    op.drop_index('idx_gp_miner_hotkey', table_name='geomagnetic_predictions')
    op.drop_table('geomagnetic_predictions')
    op.drop_table('geomagnetic_history')
    op.drop_index('idx_baseline_task_on_baseline_predictions', table_name='baseline_predictions')
    op.drop_table('baseline_predictions')
    # ### end Alembic commands ###

    # Manually added operations
    op.execute("DROP TRIGGER IF EXISTS enforce_node_table_size ON node_table;")
    op.execute("DROP FUNCTION IF EXISTS check_node_table_size();")
    print("Simplified downgrade function finished.")
    pass
