"""re_add_hotkey_index_to_node_table

Revision ID: 8a31704ff88e
Revises: 02f5e86d4224
Create Date: 2025-05-26 20:52:58.549941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a31704ff88e'
down_revision: Union[str, None] = '02f5e86d4224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_table', schema=None) as batch_op:
        batch_op.create_index('idx_node_table_hotkey', ['hotkey'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_table', schema=None) as batch_op:
        batch_op.drop_index('idx_node_table_hotkey')

    # ### end Alembic commands ###
