import fsspec
import kerchunk.hdf
import json
from typing import Dict, Any
# TODO: Add in app level short lived signed token for kerchunk json - miner will share it with validator, then only with it will valdiator be able to access the endpoint


def generate_kerchunk_json_from_local_file(
    local_netcdf_path: str, 
    target_netcdf_url: str, 
    inline_threshold: int = 300
) -> Dict[str, Any]:
    """
    Generates Kerchunk reference JSON data from a local NetCDF/HDF5 file.

    This function scans a local NetCDF file and creates a dictionary representing 
    the Kerchunk JSON references. These references point to the target URL where 
    the actual NetCDF data can be accessed by validators.

    Args:
        local_netcdf_path: The local filesystem path to the source NetCDF file.
        target_netcdf_url: The URL (e.g., 's3://...', 'http://...') or absolute path 
                           where the NetCDF file will be accessible externally. 
                           This URL is embedded in the references.
        inline_threshold: Maximum size in bytes for data chunks to be embedded 
                          directly in the JSON. Larger chunks will be referenced 
                          by their byte range in the target file. A higher value
                          can increase JSON size but might speed up loading for
                          small datasets. Defaults to 300.

    Returns:
        A dictionary containing the Kerchunk reference structure, ready to be 
        serialized to JSON.

    Raises:
        FileNotFoundError: If the local_netcdf_path does not exist.
        Exception: If any error occurs during Kerchunk processing.
    """
    try:
        # Use fsspec to open the local file
        # 'rb' mode is important for reading binary data
        with fsspec.open(f"file://{local_netcdf_path}", mode="rb") as file_obj:
            h5chunks = kerchunk.hdf.SingleHdf5ToZarr(
                file_obj, 
                target_netcdf_url, 
                inline_threshold=inline_threshold
            )
            
            # translate() converts the scanned structure into the dictionary format
            reference_dict = h5chunks.translate()
            return reference_dict
            
    except FileNotFoundError:
        print(f"Error: Local NetCDF file not found at {local_netcdf_path}")
        raise
    except Exception as e:
        print(f"Error generating Kerchunk JSON for {local_netcdf_path}: {e}")
        raise

def save_kerchunk_json(reference_dict: Dict[str, Any], output_json_path: str) -> None:
    """
    Saves the Kerchunk reference dictionary to a JSON file.

    Args:
        reference_dict: The dictionary generated by 
                          generate_kerchunk_json_from_local_file.
        output_json_path: The local filesystem path where the JSON file 
                           should be saved.
                           
    Raises:
        Exception: If any error occurs during file writing or JSON serialization.
    """
    try:
        # Use fsspec to handle writing potentially to various filesystems, 
        # though here primarily for local files. 'wb' for writing bytes.
        # We use json.dumps with encode() because fsspec expects bytes.
        with fsspec.open(output_json_path, mode="wb") as f:
            f.write(json.dumps(reference_dict).encode('utf-8'))
        print(f"Kerchunk JSON saved successfully to {output_json_path}")
    except Exception as e:
        print(f"Error saving Kerchunk JSON to {output_json_path}: {e}")
        raise

# Example Usage (can be commented out or removed in final version)
# if __name__ == '__main__':
#     # --- Configuration ---
#     local_path = "/path/to/your/local/forecast.nc" # CHANGE THIS
#     remote_url = "s3://your-bucket/forecast.nc" # CHANGE THIS (or http://..., file://...)
#     output_path = "/path/to/your/output/forecast_kerchunk.json" # CHANGE THIS
#     
#     # --- Generate & Save ---
#     try:
#         print(f"Generating Kerchunk references for: {local_path}")
#         print(f"Target URL for references: {remote_url}")
#         
#         kerchunk_refs = generate_kerchunk_json_from_local_file(
#             local_netcdf_path=local_path,
#             target_netcdf_url=remote_url
#         )
#         
#         print(f"Kerchunk references generated. Saving to: {output_path}")
#         save_kerchunk_json(kerchunk_refs, output_path)
#         
#         # Optional: Print a snippet of the generated JSON
#         # print("\nGenerated Kerchunk JSON (snippet):")
#         # print(json.dumps(kerchunk_refs, indent=2)[:1000] + "\n...") 
#         
#     except Exception as e:
#         print(f"An error occurred during the example usage: {e}") 