"""restore_last_error_column_to_soil_moisture_predictions

Revision ID: 67ea64fffc7f
Revises: aefd7993d7c1
Create Date: 2025-06-23 20:54:49.841128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ea64fffc7f'
down_revision: Union[str, None] = 'aefd7993d7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_moisture_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_moisture_predictions', schema=None) as batch_op:
        batch_op.drop_column('last_error')

    # ### end Alembic commands ###
