"""Add inference_started_at column to weather_miner_responses

Revision ID: 83c229985d5c
Revises: bc045d8f438d
Create Date: 2025-08-18 13:22:40.109689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83c229985d5c'
down_revision: Union[str, None] = 'bc045d8f438d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inference_started_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp when the miner started inference processing'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.drop_column('inference_started_at')

    # ### end Alembic commands ###
