"""add overall_forecast_score to weather_forecast_stats

Revision ID: 9445d1ec6c47
Revises: e26b04e8559f
Create Date: 2025-08-26 14:43:10.292257

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9445d1ec6c47'
down_revision: Union[str, None] = 'e26b04e8559f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecast_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_forecast_score', sa.Float(), nullable=True, comment='Unified normalized overall forecast score used for validator weighting (0-1)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_forecast_stats', schema=None) as batch_op:
        batch_op.drop_column('overall_forecast_score')

    # ### end Alembic commands ###
