"""Add singleton_key column to validator_jobs table

Revision ID: aeb6e0fada34
Revises: b7c1a2d38f10
Create Date: 2025-08-14 03:07:34.843897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb6e0fada34'
down_revision: Union[str, None] = 'b7c1a2d38f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validator_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('singleton_key', sa.String(length=255), nullable=True, comment="Unique key for singleton jobs (e.g., 'initiate_fetch_run_1')"))
        batch_op.create_index('uq_vjobs_singleton_active', ['singleton_key'], unique=True, postgresql_where=sa.text("status IN ('pending', 'claimed', 'retry_scheduled')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validator_jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_vjobs_singleton_active', postgresql_where=sa.text("status IN ('pending', 'claimed', 'retry_scheduled')"))
        batch_op.drop_column('singleton_key')

    # ### end Alembic commands ###
