"""Add sentinel_bounds and sentinel_crs to soil_moisture_history

Revision ID: aefd7993d7c1
Revises: 9184456655c8
Create Date: 2025-06-23 16:53:48.292908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aefd7993d7c1'
down_revision: Union[str, None] = '9184456655c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geomagnetic_predictions', schema=None) as batch_op:
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)

    with op.batch_alter_table('soil_moisture_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentinel_bounds', postgresql.ARRAY(sa.Float()), nullable=True))
        batch_op.add_column(sa.Column('sentinel_crs', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('unique_soil_history_per_prediction'), type_='unique')

    with op.batch_alter_table('soil_moisture_predictions', schema=None) as batch_op:
        batch_op.drop_column('last_error')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_moisture_predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('soil_moisture_history', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_soil_history_per_prediction'), ['region_id', 'miner_uid', 'target_time'])
        batch_op.drop_column('sentinel_crs')
        batch_op.drop_column('sentinel_bounds')

    with op.batch_alter_table('geomagnetic_predictions', schema=None) as batch_op:
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)

    # ### end Alembic commands ###
