"""add frozen_manifest_files to weather_miner_responses

Revision ID: bb8c9e8951c3
Revises: 9445d1ec6c47
Create Date: 2025-10-20 23:21:05.482215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb8c9e8951c3'
down_revision: Union[str, None] = '9445d1ec6c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frozen_manifest_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.drop_column('frozen_manifest_files')

    # ### end Alembic commands ###
