"""add manifest_frozen_at to weather_miner_responses

Revision ID: c9d2552f22aa
Revises: bb8c9e8951c3
Create Date: 2025-10-28 20:03:16.856051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9d2552f22aa'
down_revision: Union[str, None] = 'bb8c9e8951c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manifest_frozen_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='UTC timestamp when manifest was verified and frozen'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.drop_column('manifest_frozen_at')

    # ### end Alembic commands ###
