"""Rename forecast_inference_time to forecast_inference_duration_seconds

Revision ID: e26b04e8559f
Revises: pipeline_timing_001
Create Date: 2025-08-21 16:11:35.254128

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e26b04e8559f'
down_revision: Union[str, None] = 'pipeline_timing_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_node_fiber_key_expires'))

    with op.batch_alter_table('weather_forecast_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_inference_duration_seconds', sa.Integer(), nullable=True, comment='Time taken for inference in seconds'))
        batch_op.drop_column('forecast_inference_time')

    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_wmr_day1_completed_at'))
        batch_op.drop_index(batch_op.f('idx_wmr_era5_completed_at'))
        batch_op.drop_index(batch_op.f('idx_wmr_inference_completed_at'))
        batch_op.drop_index(batch_op.f('idx_wmr_job_accepted_at'))
        batch_op.drop_index(batch_op.f('idx_wmr_total_duration'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_miner_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_wmr_total_duration'), ['total_pipeline_duration_seconds'], unique=False)
        batch_op.create_index(batch_op.f('idx_wmr_job_accepted_at'), ['job_accepted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_wmr_inference_completed_at'), ['inference_completed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_wmr_era5_completed_at'), ['era5_scoring_completed_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_wmr_day1_completed_at'), ['day1_scoring_completed_at'], unique=False)

    with op.batch_alter_table('weather_forecast_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forecast_inference_time', sa.INTEGER(), autoincrement=False, nullable=True, comment='Time taken for inference in seconds'))
        batch_op.drop_column('forecast_inference_duration_seconds')

    with op.batch_alter_table('node_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_node_fiber_key_expires'), ['fiber_key_expires_at'], unique=False)

    # ### end Alembic commands ###
