"""drop perturb_seed table

Revision ID: f33d500dc2bc
Revises: c9d2552f22aa
Create Date: 2025-11-05 16:52:45.672518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33d500dc2bc'
down_revision: Union[str, None] = 'c9d2552f22aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perturb_seed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perturb_seed',
    sa.Column('activation_hour', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('seed_hex', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('activation_hour', name=op.f('perturb_seed_pkey'))
    )
    # ### end Alembic commands ###
